# Generated by Django 3.1.6 on 2021-02-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20210205_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='This is Blank Field', upload_to='images/')),
                ('name', models.CharField(help_text='Enter your Full Name', max_length=100)),
                ('email', models.EmailField(help_text='Enter valid Email (xyz@gmail.com)', max_length=254)),
                ('password', models.CharField(help_text='Your password must contain at least 8 characters.', max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
